### ISSUE TITLE
Multiple bugs with activity plugin in iOS

### ISSUE THREAD

**Issue by jajern** [coronalabs/plugins-source-native-popup-activity#1]
iOS v14.4
Solar2d v 2021.3637

When user starts an action inside activity window (like sharing to Facebook) and cancels, the window crashes and closes the app.

If the user continues to post to Facebook for example it does work properly and returns to the app.

Another problem I am having is if I try to share an image through the activity window and choose action text message, I am not able to send the message and also the layout of the text message display has visual bugs like the text field displaying over text history and the image being inserted is cut off by the text field only being one row high. Tapping the send icon does nothing.

**Comment by Shchvova** [comment]
Deploying the fix
